//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class all_produced_coils
    {
        public all_produced_coils()
        {
            this.coils = new HashSet<coil>();
        }
    
        public string production_coil_no { get; set; }
        public Nullable<int> cons_coil_no { get; set; }
        public Nullable<int> coil_weight { get; set; }
        public Nullable<int> coil_length { get; set; }
        public Nullable<double> coil_thickness { get; set; }
        public Nullable<double> coil_width { get; set; }
        public string coil_last_facility_ind { get; set; }
        public Nullable<System.DateTime> produced_dt_stamp { get; set; }
        public Nullable<System.DateTime> change_datetime { get; set; }
        public Nullable<int> change_user_id { get; set; }
        public Nullable<float> outside_coil_diam { get; set; }
        public string charge_coil_no { get; set; }
        public string facility_cd { get; set; }
        public string routing { get; set; }
        public string chemistry_id { get; set; }
        public string oiled { get; set; }
        public string side_trimming_mode { get; set; }
        public string staggered_wind { get; set; }
        public string chromate { get; set; }
        public Nullable<int> coating_weight { get; set; }
        public string slab_no { get; set; }
        public string grade { get; set; }
        public Nullable<float> inside_coil_diam { get; set; }
        public string status { get; set; }
        public string order_inventory { get; set; }
        public Nullable<int> origin_cd { get; set; }
        public string purchased { get; set; }
        public string snapshot { get; set; }
        public string physical_data_error { get; set; }
        public string @override { get; set; }
        public string physical_override { get; set; }
        public string test_override { get; set; }
        public string stencil { get; set; }
        public string comment { get; set; }
        public Nullable<decimal> standard_cost { get; set; }
        public string full_hard { get; set; }
        public string galvanneal { get; set; }
        public Nullable<int> processor_cd { get; set; }
        public string sdi_produced { get; set; }
        public string tolling { get; set; }
        public Nullable<int> original_cons_coil_no { get; set; }
        public string original_chemistry_id { get; set; }
        public Nullable<int> current_location { get; set; }
        public string strip_condition { get; set; }
        public string print_flag { get; set; }
        public string galv1_paint_cd { get; set; }
        public Nullable<short> mandrel_core_cd { get; set; }
        public string floor_plate { get; set; }
        public Nullable<short> trendchart_attempts { get; set; }
        public string sub_coil_status_cd { get; set; }
        public Nullable<short> packaging_type_cd { get; set; }
        public Nullable<decimal> total_cost_of_coil { get; set; }
        public string processing_po { get; set; }
        public Nullable<short> processing_po_line_item { get; set; }
        public Nullable<System.DateTime> processor_paid_dt { get; set; }
        public Nullable<decimal> freight_rate_to_processor { get; set; }
        public string internal_transport_no_charge { get; set; }
        public Nullable<decimal> theoretical_time_to_produce { get; set; }
        public string old_coil_number { get; set; }
        public string tag_no { get; set; }
        public string weight_valid { get; set; }
        public Nullable<int> coil_location_shipto_id { get; set; }
        public Nullable<System.DateTime> trg_change_datetime { get; set; }
        public Nullable<int> InventoryRecapDefPK { get; set; }
        public Nullable<int> curr_processor_cd { get; set; }
        public Nullable<int> shipped_weight { get; set; }
        public Nullable<System.DateTime> report_production_date { get; set; }
        public Nullable<double> top_coating_weight { get; set; }
        public Nullable<double> bottom_coating_weight { get; set; }
        public Nullable<byte> report_production_turn { get; set; }
        public Nullable<int> bundle_piece_count { get; set; }
        public string pw_product_type { get; set; }
        public Nullable<System.DateTime> date_blocked { get; set; }
        public Nullable<System.DateTime> date_unblocked { get; set; }
        public Nullable<int> days_produced_ahead { get; set; }
        public Nullable<int> produced_order_no { get; set; }
        public Nullable<int> produced_line_item_no { get; set; }
        public Nullable<int> consumed_order_no { get; set; }
        public Nullable<int> consumed_line_item_no { get; set; }
        public Nullable<System.DateTime> disp_date { get; set; }
        public Nullable<int> inventory_recap_corp_pk { get; set; }
        public Nullable<System.DateTime> storage_date { get; set; }
        public Nullable<int> sheet_count { get; set; }
        public Nullable<decimal> yield { get; set; }
        public string trial_id { get; set; }
        public Nullable<int> product_type_cd { get; set; }
        public string frg_production_coil_no { get; set; }
        public Nullable<decimal> purchase_price { get; set; }
        public string backoff { get; set; }
        public string crew { get; set; }
        public Nullable<int> ops_release_num { get; set; }
        public Nullable<byte> is_hot { get; set; }
        public Nullable<decimal> sheet_length { get; set; }
        public Nullable<int> coil_tmw { get; set; }
        public string is_packaged { get; set; }
        public string skid_lift_no { get; set; }
    
        public virtual ICollection<coil> coils { get; set; }
        public virtual inventory_item inventory_item { get; set; }
    }
}
