//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class application
    {
        public application()
        {
            this.application_security = new HashSet<application_security>();
        }
    
        public string application1 { get; set; }
        public string description { get; set; }
        public byte[] help_pdf { get; set; }
        public Nullable<int> idle_time { get; set; }
        public Nullable<int> tt_comp { get; set; }
        public string audit { get; set; }
        public string audit_type { get; set; }
        public string email_flag { get; set; }
        public string msg_text { get; set; }
        public Nullable<int> manager_id { get; set; }
        public string domain_specific { get; set; }
        public string application_exe { get; set; }
        public string db_flag { get; set; }
        public Nullable<System.DateTime> disabled_dt { get; set; }
        public Nullable<System.DateTime> trg_change_datetime { get; set; }
        public string in_development { get; set; }
        public string auto_ddls { get; set; }
        public string scheduled_task { get; set; }
        public string background_process { get; set; }
        public string app_pool { get; set; }
        public string auto_release { get; set; }
        public string outside_application { get; set; }
    
        public virtual ICollection<application_security> application_security { get; set; }
    }
}
