//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class application_login
    {
        public Nullable<int> user_id { get; set; }
        public string computer_name { get; set; }
        public string in_out { get; set; }
        public Nullable<int> spid { get; set; }
        public Nullable<System.DateTime> change_datetime { get; set; }
        public int pk { get; set; }
    }
}
