//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class application_security
    {
        public string user_name { get; set; }
        public string app_name { get; set; }
        public int user_id { get; set; }
        public string valid_versions { get; set; }
        public Nullable<System.DateTime> add_datetime { get; set; }
        public Nullable<int> add_user_id { get; set; }
        public Nullable<System.DateTime> change_datetime { get; set; }
        public Nullable<int> change_user_id { get; set; }
        public string user_e_mail { get; set; }
        public Nullable<int> tt_number { get; set; }
        public string release_notification { get; set; }
        public Nullable<System.DateTime> last_runtime { get; set; }
        public Nullable<System.DateTime> provisioned_date { get; set; }
        public Nullable<System.DateTime> trg_change_datetime { get; set; }
        public string alt_user_name { get; set; }
    
        public virtual user_info user_info { get; set; }
        public virtual application_security application_security1 { get; set; }
        public virtual application_security application_security2 { get; set; }
        public virtual application application { get; set; }
    }
}
