//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class application_settings
    {
        public int setting_seq { get; set; }
        public string app_name { get; set; }
        public string setting_name { get; set; }
        public string input_type { get; set; }
        public string default_value { get; set; }
        public string user_controlled { get; set; }
        public string value_format { get; set; }
        public string level3_override { get; set; }
        public string header { get; set; }
        public short height { get; set; }
        public string pb_type { get; set; }
        public string display { get; set; }
        public Nullable<int> display_order { get; set; }
    }
}
