//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ba_coil_product_data
    {
        public string production_coil_no { get; set; }
        public string workbase_no { get; set; }
        public string final_process_step { get; set; }
        public string anneal_stack_no { get; set; }
        public string grade { get; set; }
        public Nullable<int> weight { get; set; }
        public Nullable<float> strip_width { get; set; }
        public Nullable<float> strip_thickness { get; set; }
        public Nullable<short> annealing_cd { get; set; }
        public Nullable<System.DateTime> produced_dt_stamp { get; set; }
        public string valid_data_cd { get; set; }
        public string valid_data_comment { get; set; }
        public Nullable<System.DateTime> change_datetime { get; set; }
        public Nullable<int> change_user_id { get; set; }
        public string charge_coil_no { get; set; }
        public string prime { get; set; }
        public string sales_comment { get; set; }
        public string order_inventory { get; set; }
        public string status { get; set; }
        public string pes { get; set; }
        public Nullable<int> order_no { get; set; }
        public Nullable<short> line_item_no { get; set; }
        public string pay { get; set; }
        public Nullable<int> status_defect { get; set; }
        public string print_flag { get; set; }
        public Nullable<int> annealing_program_no { get; set; }
        public Nullable<int> modification_flag { get; set; }
        public string end_of_cooling_temp { get; set; }
        public string inner_cover_no { get; set; }
        public string heating_bell_no { get; set; }
        public string cooling_bell_no { get; set; }
        public Nullable<System.DateTime> inner_cover_clamped_dt_stamp { get; set; }
        public Nullable<System.DateTime> cold_leak_test_dt_stamp { get; set; }
        public Nullable<System.DateTime> air_purge_out_dt_stamp { get; set; }
        public Nullable<System.DateTime> start_heat_dt_stamp { get; set; }
        public Nullable<System.DateTime> end_heat_dt_stamp { get; set; }
        public Nullable<System.DateTime> start_cooling_dt_stamp { get; set; }
        public Nullable<System.DateTime> cooling_water_on_dt_stamp { get; set; }
        public Nullable<System.DateTime> end_cooling_dt_stamp { get; set; }
        public Nullable<int> processor_cd { get; set; }
        public string tolling { get; set; }
        public Nullable<int> original_cons_coil_no { get; set; }
        public string original_chemistry_id { get; set; }
        public string strip_condition { get; set; }
        public string sub_coil_status_cd { get; set; }
        public string old_coil_number { get; set; }
        public string tag_no { get; set; }
        public string weight_valid { get; set; }
        public Nullable<int> prod_coil_length { get; set; }
        public Nullable<System.DateTime> start_charging_dt_stamp { get; set; }
        public Nullable<System.DateTime> start_leak_test_dt_stamp { get; set; }
        public Nullable<System.DateTime> start_plug_heating_bell_dt_stamp { get; set; }
        public Nullable<System.DateTime> start_lift_heating_bell_dt_stamp { get; set; }
        public Nullable<System.DateTime> start_plug_cooling_bell_dt_stamp { get; set; }
        public Nullable<System.DateTime> start_safety_purge_dt_stamp { get; set; }
        public Nullable<System.DateTime> start_lift_cooling_bell_dt_stamp { get; set; }
        public Nullable<System.DateTime> start_release_inner_cover_dt_stamp { get; set; }
        public Nullable<System.DateTime> start_discharging_dt_stamp { get; set; }
        public Nullable<System.DateTime> start_switched_off_dt_stamp { get; set; }
        public Nullable<System.DateTime> end_charging_dt_stamp { get; set; }
        public Nullable<System.DateTime> end_leak_test_dt_stamp { get; set; }
        public Nullable<System.DateTime> end_plug_heating_bell_dt_stamp { get; set; }
        public Nullable<System.DateTime> end_lift_heating_bell_dt_stamp { get; set; }
        public Nullable<System.DateTime> end_plug_cooling_bell_dt_stamp { get; set; }
        public Nullable<System.DateTime> end_safety_purge_dt_stamp { get; set; }
        public Nullable<System.DateTime> end_lift_cooling_bell_dt_stamp { get; set; }
        public Nullable<System.DateTime> end_release_inner_cover_dt_stamp { get; set; }
        public Nullable<System.DateTime> end_discharging_dt_stamp { get; set; }
        public Nullable<System.DateTime> end_switched_off_dt_stamp { get; set; }
        public Nullable<double> sum_charging { get; set; }
        public Nullable<double> sum_leak_test { get; set; }
        public Nullable<double> sum_plug_heating_bell { get; set; }
        public Nullable<double> sum_heating { get; set; }
        public Nullable<double> sum_lift_heating_bell { get; set; }
        public Nullable<double> sum_plug_cooling_bell { get; set; }
        public Nullable<double> sum_cooling { get; set; }
        public Nullable<double> sum_safety_purge { get; set; }
        public Nullable<double> sum_lift_cooling_bell { get; set; }
        public Nullable<double> sum_release_inner_cove { get; set; }
        public Nullable<double> sum_discharging { get; set; }
        public Nullable<double> sum_switched_off { get; set; }
        public Nullable<System.DateTime> trg_change_datetime { get; set; }
        public string frg_production_coil_no { get; set; }
    }
}
