//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class carrier
    {
        public carrier()
        {
            this.shipment_load = new HashSet<shipment_load>();
        }
    
        public string carrier_mode { get; set; }
        public short carrier_cd { get; set; }
        public string name { get; set; }
        public string attention { get; set; }
        public string street_1 { get; set; }
        public string street_2 { get; set; }
        public string po_box { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip_code { get; set; }
        public string country { get; set; }
        public Nullable<System.DateTime> insurance_expire_date { get; set; }
        public string contract_number { get; set; }
        public Nullable<System.DateTime> contract_rate_expire_dt { get; set; }
        public Nullable<System.DateTime> contract_rate_effective_dt { get; set; }
        public string carrier_comments { get; set; }
        public string ap_name { get; set; }
        public string ap_attention { get; set; }
        public string ap_street1 { get; set; }
        public string ap_street2 { get; set; }
        public string ap_po_box { get; set; }
        public string ap_city { get; set; }
        public string ap_state { get; set; }
        public string ap_zip_code { get; set; }
        public string ap_country { get; set; }
        public Nullable<System.DateTime> add_datetime { get; set; }
        public Nullable<int> add_user_id { get; set; }
        public Nullable<System.DateTime> change_datetime { get; set; }
        public Nullable<int> change_user_id { get; set; }
        public Nullable<short> contact_cd { get; set; }
        public string ap_vendor_code { get; set; }
        public string ap_pay_to_code { get; set; }
        public string standard_carrier_alpha_code { get; set; }
        public string edi_id { get; set; }
        public string active { get; set; }
        public Nullable<int> from_freight_location_cd { get; set; }
        public string ships_from_sdi { get; set; }
        public string automatic_payment { get; set; }
        public Nullable<System.DateTime> automatic_payment_start_date { get; set; }
        public string exclude_freight { get; set; }
        public Nullable<int> location_carrier_cd { get; set; }
        public string edi_carrier_profile { get; set; }
        public string use_rail_lane_rate { get; set; }
    
        public virtual ICollection<shipment_load> shipment_load { get; set; }
    }
}
