//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class coil_defect
    {
        public string production_coil_no { get; set; }
        public string defect_cd { get; set; }
        public string unit_detection { get; set; }
        public string defect_comment { get; set; }
        public string defect_severity_cd { get; set; }
        public Nullable<double> strip_defect_pct { get; set; }
        public Nullable<int> defect_count { get; set; }
        public Nullable<System.DateTime> change_datetime { get; set; }
        public Nullable<int> change_user_id { get; set; }
        public Nullable<byte> top_surface { get; set; }
        public Nullable<byte> bottom_surface { get; set; }
        public Nullable<byte> body_surface { get; set; }
        public Nullable<byte> head_surface { get; set; }
        public Nullable<byte> tail_surface { get; set; }
        public Nullable<byte> operator_surface { get; set; }
        public Nullable<byte> center_surface { get; set; }
        public Nullable<byte> drive_surface { get; set; }
        public string observed_only { get; set; }
        public string inventory_or_hold { get; set; }
        public Nullable<int> order_no { get; set; }
        public Nullable<int> line_item_no { get; set; }
        public Nullable<int> cons_coil_no { get; set; }
        public string order_inventory { get; set; }
        public Nullable<System.DateTime> add_datetime { get; set; }
        public int seq_no { get; set; }
        public string reason_for_last_status_change { get; set; }
        public string unit_responsible { get; set; }
        public string flagged { get; set; }
        public Nullable<int> starting_footage { get; set; }
        public Nullable<short> length { get; set; }
        public string added_type { get; set; }
        public string @internal { get; set; }
        public Nullable<int> root_cd { get; set; }
        public string claim_back { get; set; }
        public Nullable<int> root_cd2 { get; set; }
        public Nullable<System.DateTime> trg_change_datetime { get; set; }
        public string frg_production_coil_no { get; set; }
        public string holding_defect { get; set; }
    }
}
