//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class coil_status
    {
        public string coil_status1 { get; set; }
        public string description { get; set; }
        public Nullable<byte> coil_level { get; set; }
        public Nullable<byte> coil_a { get; set; }
        public Nullable<byte> coil_b { get; set; }
        public Nullable<byte> coil_c { get; set; }
        public Nullable<System.DateTime> add_datetime { get; set; }
        public Nullable<int> add_user_id { get; set; }
        public Nullable<System.DateTime> change_datetime { get; set; }
        public Nullable<int> change_user_id { get; set; }
        public string @class { get; set; }
        public Nullable<System.DateTime> trg_change_datetime { get; set; }
        public string release_function { get; set; }
        public Nullable<short> defect_priority { get; set; }
    }
}
