//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class coil_audit_trail
    {
        public string production_coil_no { get; set; }
        public int action_seq_no { get; set; }
        public string action_description { get; set; }
        public int cons_coil_no { get; set; }
        public Nullable<int> coil_weight { get; set; }
        public Nullable<float> coil_thickness { get; set; }
        public Nullable<float> coil_width { get; set; }
        public string coil_yard_column { get; set; }
        public string coil_yard_row { get; set; }
        public string status { get; set; }
        public string status_description { get; set; }
        public string inventory_or_order { get; set; }
        public Nullable<int> order_no { get; set; }
        public Nullable<short> line_item_no { get; set; }
        public Nullable<short> line_item_coil_no { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> change_datetime { get; set; }
        public Nullable<int> change_user_id { get; set; }
        public string scanner_used { get; set; }
        public string frg_production_coil_no { get; set; }
    }
}
