//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class coil_yard_rows
    {
        public string column { get; set; }
        public string row { get; set; }
        public string carrier_mode { get; set; }
        public Nullable<int> row_capacity { get; set; }
        public Nullable<int> vacancy { get; set; }
        public Nullable<System.DateTime> add_datetime { get; set; }
        public Nullable<int> add_user_id { get; set; }
        public Nullable<System.DateTime> change_datetime { get; set; }
        public Nullable<int> change_user_id { get; set; }
        public string facility_cd { get; set; }
        public string area { get; set; }
        public string location { get; set; }
        public string dw_map_name { get; set; }
        public string bay_cd { get; set; }
        public Nullable<System.DateTime> trg_change_datetime { get; set; }
        public string Door_Id { get; set; }
        public string pallets { get; set; }
        public Nullable<int> row_ideal_capacity { get; set; }
    }
}
