//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class coil
    {
        public int order_no { get; set; }
        public short line_item_no { get; set; }
        public short line_item_coil_no { get; set; }
        public Nullable<int> string_no { get; set; }
        public Nullable<byte> heat_seq { get; set; }
        public Nullable<short> coil_prod_seq { get; set; }
        public Nullable<short> string_coil_seq { get; set; }
        public string grade { get; set; }
        public Nullable<decimal> coil_width_aim { get; set; }
        public Nullable<decimal> coil_width_min { get; set; }
        public Nullable<decimal> coil_width_max { get; set; }
        public Nullable<decimal> coil_gauge_aim { get; set; }
        public Nullable<decimal> coil_gauge_min { get; set; }
        public Nullable<decimal> coil_gauge_max { get; set; }
        public Nullable<int> coil_weight_aim { get; set; }
        public Nullable<int> coil_weight_min { get; set; }
        public Nullable<int> coil_weight_max { get; set; }
        public Nullable<short> prod_time { get; set; }
        public Nullable<System.DateTime> produced_dt_stamp { get; set; }
        public Nullable<short> process_cd { get; set; }
        public Nullable<short> tf_exit_temp { get; set; }
        public string sample_cd { get; set; }
        public string slab_crop_cd { get; set; }
        public string warmup_coil { get; set; }
        public string destn_cd { get; set; }
        public Nullable<System.DateTime> actual_ship_date { get; set; }
        public Nullable<System.DateTime> production_cycle { get; set; }
        public string coil_status { get; set; }
        public Nullable<System.DateTime> produce_by_date { get; set; }
        public string coil_indicator { get; set; }
        public Nullable<decimal> mill_width_aim { get; set; }
        public Nullable<decimal> mill_gauge_aim { get; set; }
        public Nullable<int> mill_weight_aim { get; set; }
        public Nullable<System.DateTime> scheduled_date { get; set; }
        public string coil_invoice { get; set; }
        public string coil_shipped { get; set; }
        public string disposition_status { get; set; }
        public string comment { get; set; }
        public Nullable<short> number_times_planned { get; set; }
        public string number_times_planned_comment { get; set; }
        public Nullable<short> freight_no_of_stops { get; set; }
        public Nullable<decimal> freight_price_cwt { get; set; }
        public Nullable<decimal> freight_tarping_charge { get; set; }
        public Nullable<decimal> freight_stopoff_charge { get; set; }
        public Nullable<decimal> freight_fuel_charge { get; set; }
        public Nullable<decimal> freight_insurance_charge { get; set; }
        public Nullable<System.DateTime> add_datetime { get; set; }
        public Nullable<int> add_user_id { get; set; }
        public Nullable<System.DateTime> change_datetime { get; set; }
        public Nullable<int> change_user_id { get; set; }
        public string claim_coil_no { get; set; }
        public string production_coil_no { get; set; }
        public Nullable<short> rush_order_id { get; set; }
        public Nullable<System.DateTime> pt_dt_stamp { get; set; }
        public Nullable<System.DateTime> warehouse_date { get; set; }
        public string prepaid_collect_flag { get; set; }
        public string coil_invoice_processed { get; set; }
        public string freight_invoice_processed { get; set; }
        public Nullable<decimal> shipping_freight_rate { get; set; }
        public Nullable<decimal> shipping_freight_cost { get; set; }
        public string hold_for_testing { get; set; }
        public string hold_for_testing_status { get; set; }
        public string ship_to_location_name { get; set; }
        public Nullable<decimal> freight_negotiated_rate { get; set; }
        public string freight_negotiated_rate_type { get; set; }
        public Nullable<decimal> freight_contractual_rate { get; set; }
        public Nullable<decimal> freight_billed_rate { get; set; }
        public Nullable<decimal> freight_actual_rate { get; set; }
        public Nullable<System.DateTime> freight_inv_processed { get; set; }
        public Nullable<System.DateTime> coil_inv_processed { get; set; }
        public Nullable<int> dead_freight_weight { get; set; }
        public string min_freight_apply { get; set; }
        public string warehouse_credit_to_shipping { get; set; }
        public Nullable<int> cancel_reason_cd { get; set; }
        public Nullable<int> coil_routing_cd { get; set; }
        public string tag_no { get; set; }
        public string schedule_hold { get; set; }
        public Nullable<float> claimed_gauge { get; set; }
        public Nullable<float> claimed_width { get; set; }
        public Nullable<decimal> mileage_surcharge { get; set; }
        public string return_to_sdi { get; set; }
        public string se_prepaid_collect { get; set; }
        public string release_no { get; set; }
        public Nullable<System.DateTime> transferred_to_lomas_datetime { get; set; }
        public Nullable<decimal> price_deduct { get; set; }
        public Nullable<System.DateTime> trg_change_datetime { get; set; }
        public Nullable<decimal> price_994_rule { get; set; }
        public string price_deduct_comment { get; set; }
        public Nullable<System.DateTime> report_shipment_date { get; set; }
        public string slab_comment { get; set; }
        public Nullable<int> price_deduct_user_id { get; set; }
        public Nullable<int> coil_ext_routing_cd { get; set; }
        public string remain_route { get; set; }
        public Nullable<int> transfer_order_no { get; set; }
        public Nullable<System.DateTime> otd_dt_stamp { get; set; }
        public string frg_production_coil_no { get; set; }
        public Nullable<short> slab_thickness { get; set; }
        public Nullable<decimal> freight_floating_rate { get; set; }
        public Nullable<int> priority_week { get; set; }
        public string part_no { get; set; }
        public string verification_guid { get; set; }
        public Nullable<System.DateTime> consignment_date { get; set; }
        public Nullable<System.DateTime> receive_datetime { get; set; }
    
        public virtual all_produced_coils all_produced_coils { get; set; }
        public virtual customer_order_line_item customer_order_line_item { get; set; }
    }
}
