//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public customer()
        {
            this.customer_order_line_item = new HashSet<customer_order_line_item>();
        }
    
        public int customer_id { get; set; }
        public string name { get; set; }
        public string street_1 { get; set; }
        public string street_2 { get; set; }
        public string po_box { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip_code { get; set; }
        public string country { get; set; }
        public string contact_name { get; set; }
        public string contact_title { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string tax_exempt_status { get; set; }
        public string tax_exempt_number { get; set; }
        public Nullable<int> corporate_cust_id { get; set; }
        public Nullable<short> sales_region_cd { get; set; }
        public Nullable<short> sales_rep_cd { get; set; }
        public Nullable<int> sic_cd { get; set; }
        public string cust_status { get; set; }
        public string invoice_name { get; set; }
        public string invoice_attention { get; set; }
        public string invoice_street1 { get; set; }
        public string invoice_street2 { get; set; }
        public string invoice_po_box { get; set; }
        public string invoice_city { get; set; }
        public string invoice_state { get; set; }
        public string invoice_zip_code { get; set; }
        public string invoice_country { get; set; }
        public Nullable<int> max_coil_weight { get; set; }
        public Nullable<int> min_coil_weight { get; set; }
        public string customer_type { get; set; }
        public string sent_to_ar { get; set; }
        public Nullable<int> est_annual_tonnage { get; set; }
        public string general_comments { get; set; }
        public string terms { get; set; }
        public Nullable<short> inside_sales_rep_cd { get; set; }
        public Nullable<System.DateTime> add_datetime { get; set; }
        public Nullable<int> add_user_id { get; set; }
        public Nullable<System.DateTime> change_datetime { get; set; }
        public Nullable<int> change_user_id { get; set; }
        public string business_partner { get; set; }
        public string sales_email { get; set; }
        public Nullable<System.DateTime> customer_since { get; set; }
        public Nullable<int> primary_contact_id { get; set; }
        public Nullable<int> default_buildup { get; set; }
        public string duns_no { get; set; }
        public string one_coil_per_inv { get; set; }
        public string external_process_docs { get; set; }
        public Nullable<byte> met_compare { get; set; }
        public string report_flag { get; set; }
        public Nullable<int> late_coil_weight { get; set; }
        public Nullable<int> on_time_coil_weight { get; set; }
        public Nullable<System.DateTime> last_statistics_update { get; set; }
        public string web_admin { get; set; }
        public string nasa_member { get; set; }
        public string intercompany_customer_id { get; set; }
        public Nullable<int> parent_customer_id { get; set; }
        public string allow_online_order { get; set; }
        public string customer_nick_name { get; set; }
        public string pro_forma_invoice { get; set; }
        public string invoice_method { get; set; }
        public string edi_status_report { get; set; }
        public Nullable<int> invoice_contact_id { get; set; }
        public string reliance_member { get; set; }
        public Nullable<int> techs_customer_id { get; set; }
        public Nullable<int> nasa_member_id { get; set; }
        public string allow_online_create_order { get; set; }
        public string edi_load_bulletin { get; set; }
        public string allow_online_loads { get; set; }
        public string oem_customer { get; set; }
        public string credit_hold { get; set; }
        public string special_handling { get; set; }
        public string hold_for_release { get; set; }
        public string metric_inv { get; set; }
        public string hold_refer_defects { get; set; }
        public string invoice_append { get; set; }
        public string invoice_method2 { get; set; }
        public Nullable<short> sdi_agent_cd { get; set; }
        public Nullable<short> marketing_manager_cd { get; set; }
        public Nullable<short> account_manager_cd { get; set; }
        public Nullable<decimal> sales_rep_commission_rate { get; set; }
        public string marketing_manager_commission_rate { get; set; }
        public Nullable<int> marketing_manager { get; set; }
        public Nullable<int> tech_rep { get; set; }
        public bool exclude_from_bookings { get; set; }
        public Nullable<int> frg_customer_id { get; set; }
        public Nullable<int> frg_parent_customer_id { get; set; }
        public string edi_order_ack { get; set; }
        public string iatf_automotive { get; set; }
        public string dont_include_terms { get; set; }
        public Nullable<System.DateTime> trg_change_datetime { get; set; }
        public string sdi_frg { get; set; }
        public string cust_vendor_id { get; set; }
        public string name_cont { get; set; }
        public string pricing_display_cd { get; set; }
        public string op_asn { get; set; }
        public string hfrd_address_code { get; set; }
        public string hfrd_ar_full_account { get; set; }
        public string hfrd_ar_short_code { get; set; }
        public string hfrd_cert_w_asn { get; set; }
        public string hfrd_credit_limit_code { get; set; }
        public string hfrd_customer_group { get; set; }
        public string hfrd_customer_number { get; set; }
        public string hfrd_fax { get; set; }
        public string hfrd_fax_only { get; set; }
        public string hfrd_ship_method { get; set; }
        public string hfrd_statement_account { get; set; }
        public string hfrd_sys_user_defined_3 { get; set; }
        public string hfrd_tax_exempt_number { get; set; }
        public string hfrd_tax_reference { get; set; }
        public Nullable<bool> field_reject_buyer { get; set; }
        public string marketing_mgr_commission_rate { get; set; }
        public string hfrd_OraUpd { get; set; }
        public string hfrd_intercompany { get; set; }
        public string hfrd_credit_terms_code { get; set; }
        public string tax_id_number { get; set; }
        public string internal_invoice_customer { get; set; }
        public string duns_qualifier { get; set; }
        public string generate_production_edi { get; set; }
        public bool stock_customer { get; set; }
    
        public virtual ICollection<customer_order_line_item> customer_order_line_item { get; set; }
    }
}
