//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_order_line_item
    {
        public customer_order_line_item()
        {
            this.coils = new HashSet<coil>();
        }
    
        public int order_no { get; set; }
        public short line_item_no { get; set; }
        public string ship_to_location_name { get; set; }
        public Nullable<int> product_type_cd { get; set; }
        public string material_specification_cd { get; set; }
        public string steel_design_cd { get; set; }
        public Nullable<decimal> ordered_gauge { get; set; }
        public Nullable<decimal> min_gauge { get; set; }
        public Nullable<decimal> max_gauge { get; set; }
        public Nullable<decimal> ordered_width { get; set; }
        public Nullable<decimal> min_width { get; set; }
        public Nullable<decimal> max_width { get; set; }
        public Nullable<int> ordered_weight { get; set; }
        public Nullable<int> min_weight { get; set; }
        public Nullable<int> max_weight { get; set; }
        public Nullable<int> projected_coils { get; set; }
        public Nullable<int> ordered_coil_weight { get; set; }
        public Nullable<int> min_coil_weight { get; set; }
        public Nullable<int> max_coil_weight { get; set; }
        public Nullable<int> ordered_inside_coil_diam { get; set; }
        public Nullable<int> min_inside_coil_diam { get; set; }
        public Nullable<int> max_inside_coil_diam { get; set; }
        public Nullable<decimal> ordered_outside_coil_diam { get; set; }
        public Nullable<decimal> min_outside_coil_diam { get; set; }
        public Nullable<decimal> max_outside_coil_diam { get; set; }
        public string customer_ref_no { get; set; }
        public string customer_ref_description { get; set; }
        public string spec_instruct_production { get; set; }
        public Nullable<System.DateTime> requested_date { get; set; }
        public Nullable<System.DateTime> promised_date { get; set; }
        public Nullable<System.DateTime> required_shipping_date { get; set; }
        public Nullable<System.DateTime> repromised_date { get; set; }
        public Nullable<System.DateTime> not_before_date { get; set; }
        public Nullable<System.DateTime> price_protect_date { get; set; }
        public Nullable<decimal> freight_price_cwt { get; set; }
        public string line_item_status { get; set; }
        public string metallurgy_status { get; set; }
        public string metallurgy_comment { get; set; }
        public Nullable<int> customer_id { get; set; }
        public string end_use { get; set; }
        public Nullable<System.DateTime> planned_week { get; set; }
        public string carrier_mode { get; set; }
        public string prepaid_collect_flag { get; set; }
        public Nullable<int> to_freight_location_cd { get; set; }
        public Nullable<int> from_freight_location_cd { get; set; }
        public Nullable<decimal> product_price_cwt { get; set; }
        public Nullable<int> carrier_cd { get; set; }
        public string fob { get; set; }
        public Nullable<decimal> ordered_piw { get; set; }
        public Nullable<decimal> min_piw { get; set; }
        public Nullable<decimal> max_piw { get; set; }
        public string thickness_type { get; set; }
        public Nullable<int> testing_type_cd { get; set; }
        public Nullable<decimal> thickness_tolerance { get; set; }
        public string line_item_credit_status { get; set; }
        public Nullable<System.DateTime> add_datetime { get; set; }
        public Nullable<int> add_user_id { get; set; }
        public Nullable<System.DateTime> change_datetime { get; set; }
        public Nullable<int> change_user_id { get; set; }
        public Nullable<int> mill_weight_aim { get; set; }
        public Nullable<decimal> mill_width_aim { get; set; }
        public Nullable<decimal> mill_gauge_aim { get; set; }
        public string credit_hold_prod { get; set; }
        public string credit_hold_ship { get; set; }
        public string phone_log { get; set; }
        public Nullable<System.DateTime> acknowledgement_date { get; set; }
        public Nullable<System.DateTime> re_acknowledgement_date { get; set; }
        public string coils_to_sales_hold { get; set; }
        public string sell_from_inventory { get; set; }
        public string auto_met_approve { get; set; }
        public Nullable<decimal> freight_negotiated_rate { get; set; }
        public string freight_negotiated_rate_type { get; set; }
        public string pricing_contract { get; set; }
        public Nullable<decimal> po_price { get; set; }
        public string min_freight_flag { get; set; }
        public Nullable<int> copied_order_no { get; set; }
        public Nullable<int> copied_line_item_no { get; set; }
        public string can_be_duplicated { get; set; }
        public string backlog_status { get; set; }
        public Nullable<System.DateTime> ready_to_ship_date { get; set; }
        public Nullable<System.DateTime> customer_request_date { get; set; }
        public Nullable<decimal> min_weight_buffer { get; set; }
        public Nullable<int> target_weight { get; set; }
        public Nullable<decimal> target_percentage { get; set; }
        public string po_order_no { get; set; }
        public string po_line_item_no { get; set; }
        public Nullable<System.DateTime> po_date { get; set; }
        public Nullable<int> capacity_seq_no { get; set; }
        public Nullable<int> customer_cancelled_weight { get; set; }
        public Nullable<int> sdi_cancelled_weight { get; set; }
        public Nullable<int> cancel_reason_cd { get; set; }
        public Nullable<short> replaced_by_line_item { get; set; }
        public Nullable<short> replacing_line_item { get; set; }
        public string premet_successful { get; set; }
        public Nullable<decimal> slit_width { get; set; }
        public Nullable<int> line_item_routing_cd { get; set; }
        public Nullable<short> fob_location_cd { get; set; }
        public Nullable<short> ordered_cm_inside_diam { get; set; }
        public string toll_processing_order { get; set; }
        public string quote { get; set; }
        public Nullable<int> sdi_ncca_seq { get; set; }
        public Nullable<System.DateTime> commit_date { get; set; }
        public string testing_facility { get; set; }
        public string held_facility { get; set; }
        public string invoice_surcharge_comment { get; set; }
        public Nullable<decimal> invoice_surcharge_value { get; set; }
        public string customer_indifferent_id { get; set; }
        public Nullable<int> end_user_id { get; set; }
        public string alt_steel_design_cd { get; set; }
        public string scrap_po_number { get; set; }
        public string long_term_agreement { get; set; }
        public Nullable<byte> line_item_type { get; set; }
        public string chemistry_restrictions { get; set; }
        public string material_specification_version { get; set; }
        public string sample_location { get; set; }
        public string product_origin { get; set; }
        public Nullable<decimal> ca_margin_ton { get; set; }
        public Nullable<decimal> ca_margin_hour { get; set; }
        public Nullable<System.DateTime> ca_reference_date { get; set; }
        public string source_po_number { get; set; }
        public string stop_facility { get; set; }
        public string return_to_sdi { get; set; }
        public string sdi_po_order_no { get; set; }
        public string sdi_po_line_item_no { get; set; }
        public Nullable<short> ext_ordered_cm_inside_diam { get; set; }
        public string ext_customer_indifferent_id { get; set; }
        public string ack_detail_flag { get; set; }
        public string rebuild_flag { get; set; }
        public string system_comment { get; set; }
        public string stop_facility_comment { get; set; }
        public string hold_cru { get; set; }
        public string copied_using_coil_transfer { get; set; }
        public Nullable<decimal> freight_equalization_rate { get; set; }
        public Nullable<System.DateTime> po_received_date { get; set; }
        public Nullable<System.DateTime> sales_review_datetime { get; set; }
        public Nullable<int> sales_review_user_id { get; set; }
        public string hold_at_coil_status { get; set; }
        public Nullable<int> end_use_market_id { get; set; }
        public Nullable<int> platform_id { get; set; }
        public Nullable<System.DateTime> trg_change_date_time { get; set; }
        public string PSI_ProdStatusID { get; set; }
        public string off_loader_po { get; set; }
        public string off_loader_po_li { get; set; }
        public string release_no { get; set; }
        public Nullable<bool> consignment_order { get; set; }
        public string sales_hold_facility { get; set; }
        public string pricing_method { get; set; }
        public Nullable<int> consignment_days { get; set; }
        public string all_in_pricing { get; set; }
        public string alt_material_specification_cd { get; set; }
        public Nullable<int> line_item_ext_routing_cd { get; set; }
        public Nullable<System.DateTime> reserved_datetime { get; set; }
        public Nullable<System.DateTime> cancelled_datetime { get; set; }
        public string coil_tag_comment { get; set; }
        public string billing_method { get; set; }
        public string pricing_display_cd { get; set; }
        public Nullable<decimal> op_max_od { get; set; }
        public string quote_rev_upd_exempt { get; set; }
        public string free_shipping_override { get; set; }
        public Nullable<int> heat_lot_id { get; set; }
        public Nullable<System.DateTime> trg_change_datetime { get; set; }
        public string met_spec_char { get; set; }
        public Nullable<decimal> op_min_od { get; set; }
        public string split_facility_cd { get; set; }
        public string coil_handling_hazard { get; set; }
        public Nullable<decimal> freight_floating_rate { get; set; }
        public string cycle_melt_override { get; set; }
        public Nullable<int> internal_invoice_frg_customer_id { get; set; }
        public Nullable<byte> ic_division { get; set; }
        public Nullable<int> ic_order_no { get; set; }
        public Nullable<int> ic_line_item_no { get; set; }
        public string rec_required { get; set; }
        public Nullable<decimal> min_gauge_mm { get; set; }
        public Nullable<decimal> max_gauge_mm { get; set; }
        public Nullable<decimal> ordered_gauge_mm { get; set; }
        public Nullable<decimal> min_width_mm { get; set; }
        public Nullable<decimal> max_width_mm { get; set; }
        public Nullable<decimal> ordered_width_mm { get; set; }
        public Nullable<int> min_weight_kg { get; set; }
        public Nullable<int> max_weight_kg { get; set; }
        public Nullable<int> ordered_weight_kg { get; set; }
        public Nullable<int> min_coil_weight_kg { get; set; }
        public Nullable<int> max_coil_weight_kg { get; set; }
        public Nullable<int> buildup_finish_aim_wt_kg { get; set; }
        public Nullable<decimal> min_outside_coil_diam_mm { get; set; }
        public Nullable<decimal> max_outside_coil_diam_mm { get; set; }
        public Nullable<decimal> ordered_outside_coil_diam_mm { get; set; }
        public Nullable<decimal> min_piw_mm { get; set; }
        public Nullable<decimal> max_piw_mm { get; set; }
        public Nullable<decimal> ordered_piw_mm { get; set; }
        public string int_inv_frg_cust_po { get; set; }
        public Nullable<decimal> po_price_uom { get; set; }
    
        public virtual ICollection<coil> coils { get; set; }
        public virtual customer customer { get; set; }
        public virtual customer_order customer_order { get; set; }
        public virtual hb_setup hb_setup { get; set; }
        public virtual finish_line_setup finish_line_setup { get; set; }
    }
}
