//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_order
    {
        public customer_order()
        {
            this.customer_order_line_item = new HashSet<customer_order_line_item>();
        }
    
        public int order_no { get; set; }
        public Nullable<int> customer_id { get; set; }
        public string po_number { get; set; }
        public Nullable<System.DateTime> po_date { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public Nullable<System.DateTime> acknowledgment_date { get; set; }
        public Nullable<short> testing_type_cd { get; set; }
        public Nullable<short> sales_rep_cd { get; set; }
        public string order_status { get; set; }
        public string order_pricing_method { get; set; }
        public string invoice_name { get; set; }
        public string invoice_attention { get; set; }
        public string invoice_street1 { get; set; }
        public string invoice_street2 { get; set; }
        public string invoice_po_box { get; set; }
        public string invoice_city { get; set; }
        public string invoice_zip_code { get; set; }
        public string invoice_state { get; set; }
        public string invoice_country { get; set; }
        public Nullable<System.DateTime> add_datetime { get; set; }
        public Nullable<int> add_user_id { get; set; }
        public Nullable<System.DateTime> change_datetime { get; set; }
        public Nullable<int> change_user_id { get; set; }
        public Nullable<short> inside_sales_rep_cd { get; set; }
        public string merged { get; set; }
        public string oms_to_ignore { get; set; }
        public Nullable<System.DateTime> trg_change_date_time { get; set; }
        public string coils_diverged { get; set; }
        public string using_psi_caster_weights { get; set; }
        public Nullable<System.DateTime> trg_change_datetime { get; set; }
    
        public virtual ICollection<customer_order_line_item> customer_order_line_item { get; set; }
    }
}
