//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class function_level_security
    {
        public string app_name { get; set; }
        public int user_id { get; set; }
        public string function_name { get; set; }
        public Nullable<System.DateTime> change_datetime { get; set; }
        public Nullable<int> change_user_id { get; set; }
        public string active { get; set; }
        public string function_description { get; set; }
        public Nullable<int> tt_number { get; set; }
        public Nullable<System.DateTime> provisioned_date { get; set; }
    
        public virtual function_level_description function_level_description { get; set; }
    }
}
