//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class load_dtl_bay
    {
        public int load_id { get; set; }
        public string production_coil_no { get; set; }
        public Nullable<System.DateTime> shipped_date { get; set; }
        public string load_status { get; set; }
        public string coil_yard_row { get; set; }
        public string coil_yard_column { get; set; }
        public string bay_cd { get; set; }
        public string hold { get; set; }
        public Nullable<System.DateTime> add_datetime { get; set; }
    }
}
