//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class paint_inventory
    {
        public int container_id { get; set; }
        public string paint_cd { get; set; }
        public short location_cd { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<int> number_of_gallons { get; set; }
        public Nullable<int> change_user_id { get; set; }
        public Nullable<System.DateTime> change_datetime { get; set; }
        public Nullable<System.DateTime> received_date { get; set; }
        public string batch_no { get; set; }
        public Nullable<int> container_type { get; set; }
        public string purchase_order_no { get; set; }
        public string @new { get; set; }
        public Nullable<int> po_line_item_no { get; set; }
        public string inventory_status { get; set; }
        public Nullable<int> vendor_id { get; set; }
        public int seq_no { get; set; }
        public string container_status { get; set; }
        public string initials { get; set; }
        public string vendor_container_id { get; set; }
        public Nullable<System.DateTime> reviewed { get; set; }
        public Nullable<int> receiver_no { get; set; }
        public string drum_no { get; set; }
    }
}
