//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class paint_type
    {
        public string paint_cd { get; set; }
        public string paint_description { get; set; }
        public Nullable<decimal> density { get; set; }
        public Nullable<decimal> vol_solids { get; set; }
        public Nullable<decimal> wt_solids { get; set; }
        public Nullable<int> coverage { get; set; }
        public Nullable<decimal> min_dft { get; set; }
        public Nullable<decimal> nom_dft { get; set; }
        public Nullable<decimal> max_dft { get; set; }
        public Nullable<decimal> voc { get; set; }
        public Nullable<short> gallons_per_drum { get; set; }
        public Nullable<System.DateTime> add_datetime { get; set; }
        public Nullable<int> add_user_id { get; set; }
        public Nullable<System.DateTime> change_datetime { get; set; }
        public Nullable<int> change_user_id { get; set; }
        public Nullable<decimal> weight { get; set; }
        public string package_viscosity { get; set; }
        public string suggested_reducer { get; set; }
        public string substrate { get; set; }
        public string pretreatment { get; set; }
        public string primer { get; set; }
        public string clean_up_solvents { get; set; }
        public Nullable<short> min_pmt { get; set; }
        public Nullable<decimal> color_min { get; set; }
        public Nullable<decimal> color_max { get; set; }
        public Nullable<short> gloss_min { get; set; }
        public Nullable<short> gloss_max { get; set; }
        public Nullable<short> pencil_hardness_min { get; set; }
        public Nullable<short> pencil_hardness_max { get; set; }
        public Nullable<short> solvent_resistance { get; set; }
        public Nullable<short> impact { get; set; }
        public Nullable<short> flexibility { get; set; }
        public string type { get; set; }
        public Nullable<short> max_pmt { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> vendor_id { get; set; }
        public Nullable<int> reorder_max { get; set; }
        public Nullable<int> reorder_point { get; set; }
        public string active { get; set; }
        public Nullable<int> family_cd { get; set; }
        public Nullable<int> paint_item_id { get; set; }
        public string part_no { get; set; }
        public Nullable<byte> residual_gallons { get; set; }
        public string surface_critical { get; set; }
        public Nullable<int> paint_color_family_cd { get; set; }
        public string surface_treat_facility_cd { get; set; }
        public string stock { get; set; }
        public Nullable<decimal> l_value { get; set; }
        public Nullable<decimal> a_value { get; set; }
        public Nullable<decimal> b_value { get; set; }
        public Nullable<decimal> gloss_value { get; set; }
        public string textured { get; set; }
        public string qty_based_pricing { get; set; }
        public Nullable<byte> inspection_level { get; set; }
        public Nullable<decimal> quote_price { get; set; }
        public Nullable<int> quote_coverage { get; set; }
        public string comments { get; set; }
        public Nullable<decimal> quote_vol { get; set; }
        public string retain_value { get; set; }
        public string cool_color { get; set; }
        public string msds { get; set; }
        public string rohs_compliant { get; set; }
        public Nullable<short> cross_hatch { get; set; }
        public Nullable<int> minimum_on_hand { get; set; }
        public Nullable<decimal> a_color_min { get; set; }
        public Nullable<decimal> a_color_max { get; set; }
        public Nullable<decimal> b_color_min { get; set; }
        public Nullable<decimal> b_color_max { get; set; }
        public string default_po_comment { get; set; }
        public string pdi_cd { get; set; }
        public string no_haps { get; set; }
    }
}
