//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class paint_location
    {
        public short location_cd { get; set; }
        public string loc_description { get; set; }
        public Nullable<int> change_user_id { get; set; }
        public Nullable<System.DateTime> change_datetime { get; set; }
        public string active { get; set; }
        public Nullable<int> sort_order { get; set; }
        public string paint_line_location { get; set; }
    }
}
