//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class printer_queue
    {
        public long pk { get; set; }
        public byte[] bytes { get; set; }
        public Nullable<int> printer_pk { get; set; }
        public Nullable<System.DateTime> date_inserted { get; set; }
        public Nullable<System.DateTime> date_processed { get; set; }
        public string type { get; set; }
        public string @object { get; set; }
        public Nullable<int> copies { get; set; }
        public Nullable<int> add_user_id { get; set; }
    }
}
