//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_processors
    {
        public int processor_cd { get; set; }
        public string inside_or_outside { get; set; }
        public string name { get; set; }
        public string street_1 { get; set; }
        public string street_2 { get; set; }
        public string po_box { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip_code { get; set; }
        public string country { get; set; }
        public string facility_cd { get; set; }
        public Nullable<System.DateTime> change_datetime { get; set; }
        public Nullable<int> change_user_id { get; set; }
        public string carrier_mode { get; set; }
        public string spec_instruct_receiving { get; set; }
        public string spec_instruct_mark { get; set; }
        public string spec_instruct_packing { get; set; }
        public string spec_instruct_loading { get; set; }
        public string spec_instruct_shipping { get; set; }
        public string spec_instruct_unloading { get; set; }
        public Nullable<int> to_freight_location_cd { get; set; }
        public string active { get; set; }
        public Nullable<int> shipping_contact_id { get; set; }
        public string duns_no { get; set; }
        public Nullable<decimal> production_lead_time { get; set; }
        public string sdi_produced { get; set; }
        public string facility_type { get; set; }
        public string profile { get; set; }
        public string equipment { get; set; }
        public string edi_destination { get; set; }
        public string yield_adj { get; set; }
        public Nullable<short> yield_adj_order { get; set; }
        public Nullable<int> customer_id { get; set; }
        public string edi_required { get; set; }
        public Nullable<int> vendor_no { get; set; }
        public string account_cd { get; set; }
        public Nullable<decimal> min_width { get; set; }
        public Nullable<decimal> max_width { get; set; }
        public Nullable<decimal> min_gauge { get; set; }
        public Nullable<decimal> max_gauge { get; set; }
        public Nullable<int> max_weight { get; set; }
        public Nullable<int> max_od { get; set; }
        public string default_column_location { get; set; }
        public Nullable<int> processor_parent_cd { get; set; }
        public Nullable<int> shiptoid { get; set; }
        public string old_name { get; set; }
        public string store_inside { get; set; }
        public string primary_sdi_contact { get; set; }
        public string entry_coil_yard_column { get; set; }
        public string entry_coil_yard_row { get; set; }
        public Nullable<System.DateTime> trg_change_datetime { get; set; }
        public Nullable<byte> processor_grouping { get; set; }
        public string delayed_production_edi { get; set; }
        public string op_stop { get; set; }
        public string mpo_email { get; set; }
        public string send_mpo_email { get; set; }
        public string include_internal { get; set; }
        public Nullable<int> receiver_id { get; set; }
    }
}
