//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class scanware_shipping_loads
    {
        public int load_id { get; set; }
        public Nullable<int> seq_no { get; set; }
        public Nullable<System.DateTime> entered_dt { get; set; }
        public Nullable<short> return_cd { get; set; }
    }
}
