//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sw_op_coil_validate
    {
        public string production_coil_no { get; set; }
        public Nullable<int> coil_weight { get; set; }
        public Nullable<double> coil_thickness { get; set; }
        public Nullable<double> coil_width { get; set; }
        public Nullable<int> chem_sample_no { get; set; }
        public Nullable<System.DateTime> measurement_date { get; set; }
        public Nullable<int> change_user_id { get; set; }
        public string is_valid { get; set; }
        public Nullable<System.DateTime> add_datetime { get; set; }
    }
}
