//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sw_paint_receiving
    {
        public string barcode_number { get; set; }
        public Nullable<System.DateTime> add_date_time { get; set; }
        public Nullable<int> add_user_id { get; set; }
        public Nullable<bool> scanner_used { get; set; }
        public Nullable<int> location_cd { get; set; }
    }
}
