//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_sw_print_rail_loads
    {
        public string production_coil_no { get; set; }
        public string column { get; set; }
        public string row { get; set; }
        public string packaging_type { get; set; }
        public string char_load_id { get; set; }
        public string prepaid_collect_flag { get; set; }
        public Nullable<System.DateTime> schedule_date { get; set; }
        public string carrier_name { get; set; }
        public string rail_route { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string ship_to_location_name_long { get; set; }
        public Nullable<int> coil_weight { get; set; }
        public string po_order_no { get; set; }
        public string po_line_item_no { get; set; }
        public string spec_instruct_packing { get; set; }
        public string spec_instruct_receiving { get; set; }
        public Nullable<System.DateTime> shipped_date { get; set; }
        public Nullable<System.DateTime> print_datetime { get; set; }
        public int load_id { get; set; }
        public string rail_car_type { get; set; }
        public Nullable<System.DateTime> schedule_datetime { get; set; }
        public string stage_rail { get; set; }
        public Nullable<int> coil_count { get; set; }
        public Nullable<int> total_coil_weight { get; set; }
    }
}
