//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_sw_load_details
    {
        public int load_id { get; set; }
        public long load_dtl_pk { get; set; }
        public string char_load_id { get; set; }
        public string to_ship_to_location_name { get; set; }
        public string to_ship_to_city { get; set; }
        public string to_ship_to_state { get; set; }
        public string from_ship_to_location_name { get; set; }
        public string prepaid_collect_flag { get; set; }
        public string carrier_mode { get; set; }
        public string standard_carrier_alpha_code { get; set; }
        public string carrier_name { get; set; }
        public string vehicle_no { get; set; }
        public Nullable<int> coil_weight { get; set; }
        public Nullable<double> coil_thickness { get; set; }
        public string po_order_no { get; set; }
        public Nullable<int> order_no { get; set; }
        public Nullable<System.DateTime> shipment_add_datetime { get; set; }
        public Nullable<System.DateTime> shipment_change_datetime { get; set; }
        public Nullable<System.DateTime> shipped_date { get; set; }
        public string load_status { get; set; }
        public string product_type { get; set; }
        public Nullable<short> line_item_no { get; set; }
        public string order_line_item_no { get; set; }
        public string production_coil_no { get; set; }
        public Nullable<int> customer_id { get; set; }
        public Nullable<double> coil_width { get; set; }
        public string country { get; set; }
        public string tag_no { get; set; }
    }
}
