//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_zebra_template_coil
    {
        public string production_coil_no { get; set; }
        public int pk { get; set; }
        public string name { get; set; }
        public string template { get; set; }
    }
}
