//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_shipping_schedule_334
    {
        public string production_coil_no { get; set; }
        public Nullable<int> coil_weight { get; set; }
        public string location { get; set; }
        public string bay_cd { get; set; }
        public Nullable<System.DateTime> schedule_date { get; set; }
    }
}
