//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_sw_produced_coils
    {
        public string production_coil_no { get; set; }
        public Nullable<int> coil_weight { get; set; }
        public string description { get; set; }
        public string carrier_mode { get; set; }
        public string facility_cd { get; set; }
        public Nullable<System.DateTime> produced_dt_stamp { get; set; }
        public string anneal_stack_no { get; set; }
        public string store_inside { get; set; }
    }
}
