//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_sw_inbound_op_coils
    {
        public string production_coil_no { get; set; }
        public string coil_alias { get; set; }
        public string pes_cd { get; set; }
        public Nullable<int> coil_weight { get; set; }
        public string column { get; set; }
        public string row { get; set; }
        public string next_facility_cd { get; set; }
        public string scheduled_ind { get; set; }
        public Nullable<System.DateTime> produced_dt_stamp { get; set; }
        public int order_no { get; set; }
        public string end_use_market_name { get; set; }
    }
}
