//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_sw_coil_history
    {
        public string production_coil_no { get; set; }
        public int action_seq_no { get; set; }
        public string coil_yard_column { get; set; }
        public string coil_yard_row { get; set; }
        public string action_description { get; set; }
        public Nullable<System.DateTime> change_datetime { get; set; }
        public string comment { get; set; }
        public string user_name { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string scanner_used { get; set; }
        public int cons_coil_no { get; set; }
    }
}
