//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_sw_outbound_op_coils
    {
        public string production_coil_no { get; set; }
        public string coil_alias { get; set; }
        public string pes_cd { get; set; }
        public string ship_to_location_name { get; set; }
        public Nullable<int> coil_weight { get; set; }
        public string column { get; set; }
        public string row { get; set; }
        public int order_no { get; set; }
        public string char_load_id { get; set; }
        public string description { get; set; }
        public int load_id { get; set; }
        public Nullable<byte> is_hot { get; set; }
    }
}
