//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_sw_scheduled_coils
    {
        public string production_coil_no { get; set; }
        public string coil_alias { get; set; }
        public string facility_cd { get; set; }
        public Nullable<short> prod_seq { get; set; }
        public Nullable<int> coil_weight { get; set; }
        public string column { get; set; }
        public string row { get; set; }
        public string schedule_number { get; set; }
    }
}
