//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class warehoused_load_dtl
    {
        public int seq_no { get; set; }
        public Nullable<int> load_id { get; set; }
        public string production_coil_no { get; set; }
        public Nullable<int> coil_weight { get; set; }
        public Nullable<System.DateTime> coil_scanned_dt { get; set; }
        public Nullable<System.DateTime> add_datetime { get; set; }
        public Nullable<int> add_user_id { get; set; }
        public Nullable<System.DateTime> change_datetime { get; set; }
        public Nullable<int> change_user_id { get; set; }
    }
}
