//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanware.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class warehoused_inventory
    {
        public string production_coil_no { get; set; }
        public string warehouse_status_cd { get; set; }
        public Nullable<int> customer_id { get; set; }
        public string ship_to_location_name { get; set; }
        public Nullable<System.DateTime> actual_ship_date { get; set; }
        public Nullable<System.DateTime> inv_processed { get; set; }
        public Nullable<decimal> freight_negotiated_rate { get; set; }
        public Nullable<decimal> freight_contractual_rate { get; set; }
        public Nullable<System.DateTime> add_datetime { get; set; }
        public Nullable<int> add_user_id { get; set; }
        public Nullable<System.DateTime> change_datetime { get; set; }
        public Nullable<int> change_user_id { get; set; }
        public string coil_tag_units { get; set; }
    }
}
