//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scanware.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Scanware.Properties.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string button_clear {
            get {
                return ResourceManager.GetString("button_clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string button_confirm {
            get {
                return ResourceManager.GetString("button_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string button_print {
            get {
                return ResourceManager.GetString("button_print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string button_reset {
            get {
                return ResourceManager.GetString("button_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string button_search {
            get {
                return ResourceManager.GetString("button_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while checking in.
        /// </summary>
        public static string error_check_in_failed {
            get {
                return ResourceManager.GetString("error_check_in_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment is scheduled for .
        /// </summary>
        public static string error_future_shipment {
            get {
                return ResourceManager.GetString("error_future_shipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Load Card Number.
        /// </summary>
        public static string error_invalid_load_card_number {
            get {
                return ResourceManager.GetString("error_invalid_load_card_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Pre-Check Number.
        /// </summary>
        public static string error_invalid_precheck_number {
            get {
                return ResourceManager.GetString("error_invalid_precheck_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This terminal can not be used for MSP or NEW PROCESS-COLUMBUS Shipments.
        /// </summary>
        public static string error_local_destination {
            get {
                return ResourceManager.GetString("error_local_destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is destined for.
        /// </summary>
        public static string error_local_destination_supplement {
            get {
                return ResourceManager.GetString("error_local_destination_supplement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find Pre-Check ID.
        /// </summary>
        public static string error_precheck_id_not_found {
            get {
                return ResourceManager.GetString("error_precheck_id_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This load has already been shipped.
        /// </summary>
        public static string error_previous_shipment {
            get {
                return ResourceManager.GetString("error_previous_shipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while printing ship tag / load cards. Please contact IT support..
        /// </summary>
        public static string error_print_failed {
            get {
                return ResourceManager.GetString("error_print_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while attempting to save the signature. Please contact IT support..
        /// </summary>
        public static string error_signature_failed {
            get {
                return ResourceManager.GetString("error_signature_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No signature was captured. Signature is required..
        /// </summary>
        public static string error_signature_required {
            get {
                return ResourceManager.GetString("error_signature_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination does not match customer order.
        /// </summary>
        public static string error_validation_failed {
            get {
                return ResourceManager.GetString("error_validation_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string header_coil_location {
            get {
                return ResourceManager.GetString("header_coil_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Status.
        /// </summary>
        public static string header_coil_verification_status {
            get {
                return ResourceManager.GetString("header_coil_verification_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string header_coil_weight {
            get {
                return ResourceManager.GetString("header_coil_weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Type.
        /// </summary>
        public static string header_product_type {
            get {
                return ResourceManager.GetString("header_product_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coil Number.
        /// </summary>
        public static string header_production_coil_no {
            get {
                return ResourceManager.GetString("header_production_coil_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Pick Up Description.
        /// </summary>
        public static string input_customer_pickup_description {
            get {
                return ResourceManager.GetString("input_customer_pickup_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select destination State and City and click Confirm.
        /// </summary>
        public static string instructions_step1 {
            get {
                return ResourceManager.GetString("instructions_step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your vehicle number, verify carrier, and click Confirm..
        /// </summary>
        public static string instructions_step2 {
            get {
                return ResourceManager.GetString("instructions_step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your name, use the touch screen to sign in the blue box, and click Confirm..
        /// </summary>
        public static string instructions_step3 {
            get {
                return ResourceManager.GetString("instructions_step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify the details below and click Confirm to print your shipping paperwork..
        /// </summary>
        public static string instructions_step4 {
            get {
                return ResourceManager.GetString("instructions_step4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier.
        /// </summary>
        public static string label_carrier {
            get {
                return ResourceManager.GetString("label_carrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string label_city {
            get {
                return ResourceManager.GetString("label_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unverified.
        /// </summary>
        public static string label_coil_unverified {
            get {
                return ResourceManager.GetString("label_coil_unverified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified.
        /// </summary>
        public static string label_coil_verified {
            get {
                return ResourceManager.GetString("label_coil_verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        public static string label_destination {
            get {
                return ResourceManager.GetString("label_destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Name.
        /// </summary>
        public static string label_driver_name {
            get {
                return ResourceManager.GetString("label_driver_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        public static string label_driver_signature {
            get {
                return ResourceManager.GetString("label_driver_signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string label_error {
            get {
                return ResourceManager.GetString("label_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future Shipment.
        /// </summary>
        public static string label_future_shipment {
            get {
                return ResourceManager.GetString("label_future_shipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Card Number.
        /// </summary>
        public static string label_load_card_number {
            get {
                return ResourceManager.GetString("label_load_card_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Details.
        /// </summary>
        public static string label_load_details {
            get {
                return ResourceManager.GetString("label_load_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string label_message {
            get {
                return ResourceManager.GetString("label_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Check Number.
        /// </summary>
        public static string label_precheck_prompt {
            get {
                return ResourceManager.GetString("label_precheck_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string label_previous_shipment {
            get {
                return ResourceManager.GetString("label_previous_shipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Time.
        /// </summary>
        public static string label_processed_time {
            get {
                return ResourceManager.GetString("label_processed_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string label_state {
            get {
                return ResourceManager.GetString("label_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Number.
        /// </summary>
        public static string label_vehicle_number {
            get {
                return ResourceManager.GetString("label_vehicle_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        public static string progress_stage_0 {
            get {
                return ResourceManager.GetString("progress_stage_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier Info.
        /// </summary>
        public static string progress_stage_1 {
            get {
                return ResourceManager.GetString("progress_stage_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        public static string progress_stage_2 {
            get {
                return ResourceManager.GetString("progress_stage_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string progress_stage_3 {
            get {
                return ResourceManager.GetString("progress_stage_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Carrier.
        /// </summary>
        public static string prompt_select_carrier {
            get {
                return ResourceManager.GetString("prompt_select_carrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select City.
        /// </summary>
        public static string prompt_select_city {
            get {
                return ResourceManager.GetString("prompt_select_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select State.
        /// </summary>
        public static string prompt_select_state {
            get {
                return ResourceManager.GetString("prompt_select_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-In Complete. Printing Load Card &amp; Bill of Lading.
        /// </summary>
        public static string success_message {
            get {
                return ResourceManager.GetString("success_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiosk.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prechecked.
        /// </summary>
        public static string toggle_prechecked {
            get {
                return ResourceManager.GetString("toggle_prechecked", resourceCulture);
            }
        }
    }
}
